name: Publish package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run:  |
          npm ci
          npm run build

      - name: Publish package to GitHub and NPM
        uses: ava-cassiopeia/publish-to-npm-and-github@fcc1b9754b4fd36ab757a1f5712164bdf2405c95
        with:
          npm-package-name: 'a-simple-switch'
          github-package-name: '@ava-cassiopeia/a-simple-switch'
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
